Docs: add information architecture
GRUPO-3-MOVILES/upc-pre-202402-cc-238-WV61-WeHaveAnIdea-report pull request #57
Opened 2024-09-10 17:04 UTC by AldhaValenzuelaH

2024-09-10 19:30 UTC, LucioY250 reviewed
-Corregir "Roadmecis" en todo el texto

-En searching system, el punto 4 es incorrecto.

- En navigation system Especificar todos las "etiquetas" que serán botones que lleven a otros apartados. (home (posts), profile, notifications, Roadmpas, inbox) profile contendra un sidebar

2024-09-10 19:33 UTC, LucioY250 requested changes
-Corregir "Roadmecis" en todo el texto

-En searching system, el punto 4 es incorrecto.

En navigation system Especificar todos las "etiquetas" que serán botones que lleven a otros apartados. (home (posts), profile, notifications, Roadmpas, inbox) profile contendra un sidebar

2024-09-10 23:18 UTC, AldhaValenzuelaH commented
Resuelto, revisa.

2024-09-11 03:26 UTC, LucioY250 requested changes
Corregir líneas 154-163-175-209 "Roadmecis"

BORRA EL PUNTO 4 SECCION INFERIOR

EL PATRON F NO CORRESPONDE CON NUESTRO DISEÑO


ABUSIVO

2024-09-11 03:59 UTC, LucioY250 requested changes
CORRIGE

2024-09-11 04:59 UTC, LucioY250 approved these changes

2024-09-11 04:59 UTC, merged